# Generated by Django 5.2.12 on 2026-03-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userApp", "0002_alter_otp_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="code",
            field=models.CharField(max_length=6, null=True),
        ),
    ]
